//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", ConfigurationName="RegistroContratoSoap")]
public interface RegistroContratoSoap
{
    
    // CODEGEN: Gerando contrato de mensagem porque a mensagem RegistrarContratoRequest tem cabeçalhos
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/RegistrarContrato", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resultado))]
    RegistrarContratoResponse RegistrarContrato(RegistrarContratoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/RegistrarContrato", ReplyAction="*")]
    System.Threading.Tasks.Task<RegistrarContratoResponse> RegistrarContratoAsync(RegistrarContratoRequest request);
    
    // CODEGEN: Gerando contrato de mensagem porque a mensagem ConsultarSequencialContratoRequest tem cabeçalhos
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/ConsultarSequencialContrato" +
        "", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resultado))]
    ConsultarSequencialContratoResponse ConsultarSequencialContrato(ConsultarSequencialContratoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/ConsultarSequencialContrato" +
        "", ReplyAction="*")]
    System.Threading.Tasks.Task<ConsultarSequencialContratoResponse> ConsultarSequencialContratoAsync(ConsultarSequencialContratoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/TrocarSenha", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resultado))]
    ResultadoTrocarSenha TrocarSenha(DadosTrocaSenha Dados);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/TrocarSenha", ReplyAction="*")]
    System.Threading.Tasks.Task<ResultadoTrocarSenha> TrocarSenhaAsync(DadosTrocaSenha Dados);
    
    // CODEGEN: Gerando contrato de mensagem porque a mensagem AnexarArquivoRequest tem cabeçalhos
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/AnexarArquivo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Resultado))]
    AnexarArquivoResponse AnexarArquivo(AnexarArquivoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://webservicesh.sc.gov.br/detran/RegistroContrato/AnexarArquivo", ReplyAction="*")]
    System.Threading.Tasks.Task<AnexarArquivoResponse> AnexarArquivoAsync(AnexarArquivoRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class Credenciais
{
    
    private string usuarioField;
    
    private string senhaField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Usuario
    {
        get
        {
            return this.usuarioField;
        }
        set
        {
            this.usuarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Senha
    {
        get
        {
            return this.senhaField;
        }
        set
        {
            this.senhaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class DadosAnexarArquivo
{
    
    private int sequencialContratoField;
    
    private int sequencialAditivoField;
    
    private byte[] arquivoContratoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int SequencialContrato
    {
        get
        {
            return this.sequencialContratoField;
        }
        set
        {
            this.sequencialContratoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int SequencialAditivo
    {
        get
        {
            return this.sequencialAditivoField;
        }
        set
        {
            this.sequencialAditivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
    public byte[] ArquivoContrato
    {
        get
        {
            return this.arquivoContratoField;
        }
        set
        {
            this.arquivoContratoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class DadosTrocaSenha
{
    
    private string usuarioField;
    
    private string senhaAntigaField;
    
    private string senhaNovaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Usuario
    {
        get
        {
            return this.usuarioField;
        }
        set
        {
            this.usuarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string SenhaAntiga
    {
        get
        {
            return this.senhaAntigaField;
        }
        set
        {
            this.senhaAntigaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SenhaNova
    {
        get
        {
            return this.senhaNovaField;
        }
        set
        {
            this.senhaNovaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class DadosConsultaSequencial
{
    
    private string chassiField;
    
    private int remarcacaoField;
    
    private string cNPJAgenteField;
    
    private int numGravameField;
    
    private int tipoGravameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Chassi
    {
        get
        {
            return this.chassiField;
        }
        set
        {
            this.chassiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int Remarcacao
    {
        get
        {
            return this.remarcacaoField;
        }
        set
        {
            this.remarcacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string CNPJAgente
    {
        get
        {
            return this.cNPJAgenteField;
        }
        set
        {
            this.cNPJAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int NumGravame
    {
        get
        {
            return this.numGravameField;
        }
        set
        {
            this.numGravameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int TipoGravame
    {
        get
        {
            return this.tipoGravameField;
        }
        set
        {
            this.tipoGravameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoAnexarArquivo))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoTrocarSenha))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoConsultaSequencial))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultadoRegistroContrato))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public abstract partial class Resultado
{
    
    private int codRetornoField;
    
    private string descRetornoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int CodRetorno
    {
        get
        {
            return this.codRetornoField;
        }
        set
        {
            this.codRetornoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string DescRetorno
    {
        get
        {
            return this.descRetornoField;
        }
        set
        {
            this.descRetornoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class ResultadoAnexarArquivo : Resultado
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class ResultadoTrocarSenha : Resultado
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class ResultadoConsultaSequencial : Resultado
{
    
    private int sequencialContratoField;
    
    private int sequencialAditivoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int SequencialContrato
    {
        get
        {
            return this.sequencialContratoField;
        }
        set
        {
            this.sequencialContratoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int SequencialAditivo
    {
        get
        {
            return this.sequencialAditivoField;
        }
        set
        {
            this.sequencialAditivoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class ResultadoRegistroContrato : Resultado
{
    
    private int sequencialContratoField;
    
    private int sequencialAditivoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int SequencialContrato
    {
        get
        {
            return this.sequencialContratoField;
        }
        set
        {
            this.sequencialContratoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int SequencialAditivo
    {
        get
        {
            return this.sequencialAditivoField;
        }
        set
        {
            this.sequencialAditivoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
public partial class DadosRegistroContrato
{
    
    private int tipoOperacaoField;
    
    private int sequencialContratoField;
    
    private string chassiField;
    
    private int remarcacaoField;
    
    private string uFPlacaField;
    
    private string placaField;
    
    private long rENAVAMField;
    
    private int anoFabricacaoField;
    
    private int anoModeloField;
    
    private string nomeAgenteField;
    
    private string cNPJAgenteField;
    
    private string numContratoField;
    
    private int dataContratoField;
    
    private int qtdParcelasField;
    
    private int numGravameField;
    
    private int tipoGravameField;
    
    private int taxaJuroMesField;
    
    private int taxaJuroAnoField;
    
    private string taxaJuroMultaField;
    
    private string taxaMoraDiaField;
    
    private int taxaMultaField;
    
    private int taxaMoraField;
    
    private string indicativoPenalidadeField;
    
    private string penalidadeField;
    
    private string indicativoComissaoField;
    
    private int comissaoField;
    
    private int valorTaxaContratoField;
    
    private int valorTotalFinanciamentoField;
    
    private int valorIOFField;
    
    private int valorParcelaField;
    
    private int dataVectoPrimeiraParcelaField;
    
    private int dataVectoUltimaParcelaField;
    
    private int dataLiberacaoCreditoField;
    
    private string uFLiberacaoCreditoField;
    
    private string municipioLiberacaoCreditoField;
    
    private string indiceField;
    
    private string numGrupoConsorcioField;
    
    private int numCotaConsorcioField;
    
    private string numAditivoField;
    
    private int dataAditivoField;
    
    private string nomeLogradouroAgenteField;
    
    private string numImovelAgenteField;
    
    private string complementoImovelAgenteField;
    
    private string bairroAgenteField;
    
    private string nomeMunicipioAgenteField;
    
    private string uFAgenteField;
    
    private int cEPAgenteField;
    
    private int dDDAgenteField;
    
    private string telefoneAgenteField;
    
    private string cPFCNPJDevedorField;
    
    private string nomeDevedorField;
    
    private string nomeLogradouroDevedorField;
    
    private string numImovelDevedorField;
    
    private string complementoImovelDevedorField;
    
    private string bairroDevedorField;
    
    private string nomeMunicipioDevedorField;
    
    private string uFDevedorField;
    
    private int cEPDevedorField;
    
    private int dDDDevedorField;
    
    private string telefoneDevedorField;
    
    private string uFLicenciamentoField;
    
    private string numContratoOrigemField;
    
    private string numAditivoOrigemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int TipoOperacao
    {
        get
        {
            return this.tipoOperacaoField;
        }
        set
        {
            this.tipoOperacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int SequencialContrato
    {
        get
        {
            return this.sequencialContratoField;
        }
        set
        {
            this.sequencialContratoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Chassi
    {
        get
        {
            return this.chassiField;
        }
        set
        {
            this.chassiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int Remarcacao
    {
        get
        {
            return this.remarcacaoField;
        }
        set
        {
            this.remarcacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string UFPlaca
    {
        get
        {
            return this.uFPlacaField;
        }
        set
        {
            this.uFPlacaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Placa
    {
        get
        {
            return this.placaField;
        }
        set
        {
            this.placaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public long RENAVAM
    {
        get
        {
            return this.rENAVAMField;
        }
        set
        {
            this.rENAVAMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public int AnoFabricacao
    {
        get
        {
            return this.anoFabricacaoField;
        }
        set
        {
            this.anoFabricacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public int AnoModelo
    {
        get
        {
            return this.anoModeloField;
        }
        set
        {
            this.anoModeloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string NomeAgente
    {
        get
        {
            return this.nomeAgenteField;
        }
        set
        {
            this.nomeAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string CNPJAgente
    {
        get
        {
            return this.cNPJAgenteField;
        }
        set
        {
            this.cNPJAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string NumContrato
    {
        get
        {
            return this.numContratoField;
        }
        set
        {
            this.numContratoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public int DataContrato
    {
        get
        {
            return this.dataContratoField;
        }
        set
        {
            this.dataContratoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public int QtdParcelas
    {
        get
        {
            return this.qtdParcelasField;
        }
        set
        {
            this.qtdParcelasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public int NumGravame
    {
        get
        {
            return this.numGravameField;
        }
        set
        {
            this.numGravameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public int TipoGravame
    {
        get
        {
            return this.tipoGravameField;
        }
        set
        {
            this.tipoGravameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public int TaxaJuroMes
    {
        get
        {
            return this.taxaJuroMesField;
        }
        set
        {
            this.taxaJuroMesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public int TaxaJuroAno
    {
        get
        {
            return this.taxaJuroAnoField;
        }
        set
        {
            this.taxaJuroAnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public string TaxaJuroMulta
    {
        get
        {
            return this.taxaJuroMultaField;
        }
        set
        {
            this.taxaJuroMultaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public string TaxaMoraDia
    {
        get
        {
            return this.taxaMoraDiaField;
        }
        set
        {
            this.taxaMoraDiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public int TaxaMulta
    {
        get
        {
            return this.taxaMultaField;
        }
        set
        {
            this.taxaMultaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public int TaxaMora
    {
        get
        {
            return this.taxaMoraField;
        }
        set
        {
            this.taxaMoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public string IndicativoPenalidade
    {
        get
        {
            return this.indicativoPenalidadeField;
        }
        set
        {
            this.indicativoPenalidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public string Penalidade
    {
        get
        {
            return this.penalidadeField;
        }
        set
        {
            this.penalidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=24)]
    public string IndicativoComissao
    {
        get
        {
            return this.indicativoComissaoField;
        }
        set
        {
            this.indicativoComissaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=25)]
    public int Comissao
    {
        get
        {
            return this.comissaoField;
        }
        set
        {
            this.comissaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=26)]
    public int ValorTaxaContrato
    {
        get
        {
            return this.valorTaxaContratoField;
        }
        set
        {
            this.valorTaxaContratoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=27)]
    public int ValorTotalFinanciamento
    {
        get
        {
            return this.valorTotalFinanciamentoField;
        }
        set
        {
            this.valorTotalFinanciamentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=28)]
    public int ValorIOF
    {
        get
        {
            return this.valorIOFField;
        }
        set
        {
            this.valorIOFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=29)]
    public int ValorParcela
    {
        get
        {
            return this.valorParcelaField;
        }
        set
        {
            this.valorParcelaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=30)]
    public int DataVectoPrimeiraParcela
    {
        get
        {
            return this.dataVectoPrimeiraParcelaField;
        }
        set
        {
            this.dataVectoPrimeiraParcelaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=31)]
    public int DataVectoUltimaParcela
    {
        get
        {
            return this.dataVectoUltimaParcelaField;
        }
        set
        {
            this.dataVectoUltimaParcelaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=32)]
    public int DataLiberacaoCredito
    {
        get
        {
            return this.dataLiberacaoCreditoField;
        }
        set
        {
            this.dataLiberacaoCreditoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=33)]
    public string UFLiberacaoCredito
    {
        get
        {
            return this.uFLiberacaoCreditoField;
        }
        set
        {
            this.uFLiberacaoCreditoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=34)]
    public string MunicipioLiberacaoCredito
    {
        get
        {
            return this.municipioLiberacaoCreditoField;
        }
        set
        {
            this.municipioLiberacaoCreditoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=35)]
    public string Indice
    {
        get
        {
            return this.indiceField;
        }
        set
        {
            this.indiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=36)]
    public string NumGrupoConsorcio
    {
        get
        {
            return this.numGrupoConsorcioField;
        }
        set
        {
            this.numGrupoConsorcioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=37)]
    public int NumCotaConsorcio
    {
        get
        {
            return this.numCotaConsorcioField;
        }
        set
        {
            this.numCotaConsorcioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=38)]
    public string NumAditivo
    {
        get
        {
            return this.numAditivoField;
        }
        set
        {
            this.numAditivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=39)]
    public int DataAditivo
    {
        get
        {
            return this.dataAditivoField;
        }
        set
        {
            this.dataAditivoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=40)]
    public string NomeLogradouroAgente
    {
        get
        {
            return this.nomeLogradouroAgenteField;
        }
        set
        {
            this.nomeLogradouroAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=41)]
    public string NumImovelAgente
    {
        get
        {
            return this.numImovelAgenteField;
        }
        set
        {
            this.numImovelAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=42)]
    public string ComplementoImovelAgente
    {
        get
        {
            return this.complementoImovelAgenteField;
        }
        set
        {
            this.complementoImovelAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=43)]
    public string BairroAgente
    {
        get
        {
            return this.bairroAgenteField;
        }
        set
        {
            this.bairroAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=44)]
    public string NomeMunicipioAgente
    {
        get
        {
            return this.nomeMunicipioAgenteField;
        }
        set
        {
            this.nomeMunicipioAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=45)]
    public string UFAgente
    {
        get
        {
            return this.uFAgenteField;
        }
        set
        {
            this.uFAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=46)]
    public int CEPAgente
    {
        get
        {
            return this.cEPAgenteField;
        }
        set
        {
            this.cEPAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=47)]
    public int DDDAgente
    {
        get
        {
            return this.dDDAgenteField;
        }
        set
        {
            this.dDDAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=48)]
    public string TelefoneAgente
    {
        get
        {
            return this.telefoneAgenteField;
        }
        set
        {
            this.telefoneAgenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=49)]
    public string CPFCNPJDevedor
    {
        get
        {
            return this.cPFCNPJDevedorField;
        }
        set
        {
            this.cPFCNPJDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=50)]
    public string NomeDevedor
    {
        get
        {
            return this.nomeDevedorField;
        }
        set
        {
            this.nomeDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=51)]
    public string NomeLogradouroDevedor
    {
        get
        {
            return this.nomeLogradouroDevedorField;
        }
        set
        {
            this.nomeLogradouroDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=52)]
    public string NumImovelDevedor
    {
        get
        {
            return this.numImovelDevedorField;
        }
        set
        {
            this.numImovelDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=53)]
    public string ComplementoImovelDevedor
    {
        get
        {
            return this.complementoImovelDevedorField;
        }
        set
        {
            this.complementoImovelDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=54)]
    public string BairroDevedor
    {
        get
        {
            return this.bairroDevedorField;
        }
        set
        {
            this.bairroDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=55)]
    public string NomeMunicipioDevedor
    {
        get
        {
            return this.nomeMunicipioDevedorField;
        }
        set
        {
            this.nomeMunicipioDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=56)]
    public string UFDevedor
    {
        get
        {
            return this.uFDevedorField;
        }
        set
        {
            this.uFDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=57)]
    public int CEPDevedor
    {
        get
        {
            return this.cEPDevedorField;
        }
        set
        {
            this.cEPDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=58)]
    public int DDDDevedor
    {
        get
        {
            return this.dDDDevedorField;
        }
        set
        {
            this.dDDDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=59)]
    public string TelefoneDevedor
    {
        get
        {
            return this.telefoneDevedorField;
        }
        set
        {
            this.telefoneDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=60)]
    public string UFLicenciamento
    {
        get
        {
            return this.uFLicenciamentoField;
        }
        set
        {
            this.uFLicenciamentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=61)]
    public string NumContratoOrigem
    {
        get
        {
            return this.numContratoOrigemField;
        }
        set
        {
            this.numContratoOrigemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=62)]
    public string NumAditivoOrigem
    {
        get
        {
            return this.numAditivoOrigemField;
        }
        set
        {
            this.numAditivoOrigemField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarContrato", WrapperNamespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", IsWrapped=true)]
public partial class RegistrarContratoRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
    public Credenciais Credenciais;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", Order=0)]
    public DadosRegistroContrato Dados;
    
    public RegistrarContratoRequest()
    {
    }
    
    public RegistrarContratoRequest(Credenciais Credenciais, DadosRegistroContrato Dados)
    {
        this.Credenciais = Credenciais;
        this.Dados = Dados;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarContratoResponse", WrapperNamespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", IsWrapped=true)]
public partial class RegistrarContratoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", Order=0)]
    public ResultadoRegistroContrato RegistrarContratoResult;
    
    public RegistrarContratoResponse()
    {
    }
    
    public RegistrarContratoResponse(ResultadoRegistroContrato RegistrarContratoResult)
    {
        this.RegistrarContratoResult = RegistrarContratoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSequencialContrato", WrapperNamespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", IsWrapped=true)]
public partial class ConsultarSequencialContratoRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
    public Credenciais Credenciais;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", Order=0)]
    public DadosConsultaSequencial Dados;
    
    public ConsultarSequencialContratoRequest()
    {
    }
    
    public ConsultarSequencialContratoRequest(Credenciais Credenciais, DadosConsultaSequencial Dados)
    {
        this.Credenciais = Credenciais;
        this.Dados = Dados;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSequencialContratoResponse", WrapperNamespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", IsWrapped=true)]
public partial class ConsultarSequencialContratoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", Order=0)]
    public ResultadoConsultaSequencial ConsultarSequencialContratoResult;
    
    public ConsultarSequencialContratoResponse()
    {
    }
    
    public ConsultarSequencialContratoResponse(ResultadoConsultaSequencial ConsultarSequencialContratoResult)
    {
        this.ConsultarSequencialContratoResult = ConsultarSequencialContratoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="AnexarArquivo", WrapperNamespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", IsWrapped=true)]
public partial class AnexarArquivoRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato")]
    public Credenciais Credenciais;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", Order=0)]
    public DadosAnexarArquivo Dados;
    
    public AnexarArquivoRequest()
    {
    }
    
    public AnexarArquivoRequest(Credenciais Credenciais, DadosAnexarArquivo Dados)
    {
        this.Credenciais = Credenciais;
        this.Dados = Dados;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="AnexarArquivoResponse", WrapperNamespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", IsWrapped=true)]
public partial class AnexarArquivoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservicesh.sc.gov.br/detran/RegistroContrato", Order=0)]
    public ResultadoAnexarArquivo AnexarArquivoResult;
    
    public AnexarArquivoResponse()
    {
    }
    
    public AnexarArquivoResponse(ResultadoAnexarArquivo AnexarArquivoResult)
    {
        this.AnexarArquivoResult = AnexarArquivoResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface RegistroContratoSoapChannel : RegistroContratoSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RegistroContratoSoapClient : System.ServiceModel.ClientBase<RegistroContratoSoap>, RegistroContratoSoap
{
    
    public RegistroContratoSoapClient()
    {
    }
    
    public RegistroContratoSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RegistroContratoSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegistroContratoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RegistroContratoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RegistrarContratoResponse RegistroContratoSoap.RegistrarContrato(RegistrarContratoRequest request)
    {
        return base.Channel.RegistrarContrato(request);
    }
    
    public ResultadoRegistroContrato RegistrarContrato(Credenciais Credenciais, DadosRegistroContrato Dados)
    {
        RegistrarContratoRequest inValue = new RegistrarContratoRequest();
        inValue.Credenciais = Credenciais;
        inValue.Dados = Dados;
        RegistrarContratoResponse retVal = ((RegistroContratoSoap)(this)).RegistrarContrato(inValue);
        return retVal.RegistrarContratoResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<RegistrarContratoResponse> RegistroContratoSoap.RegistrarContratoAsync(RegistrarContratoRequest request)
    {
        return base.Channel.RegistrarContratoAsync(request);
    }
    
    public System.Threading.Tasks.Task<RegistrarContratoResponse> RegistrarContratoAsync(Credenciais Credenciais, DadosRegistroContrato Dados)
    {
        RegistrarContratoRequest inValue = new RegistrarContratoRequest();
        inValue.Credenciais = Credenciais;
        inValue.Dados = Dados;
        return ((RegistroContratoSoap)(this)).RegistrarContratoAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ConsultarSequencialContratoResponse RegistroContratoSoap.ConsultarSequencialContrato(ConsultarSequencialContratoRequest request)
    {
        return base.Channel.ConsultarSequencialContrato(request);
    }
    
    public ResultadoConsultaSequencial ConsultarSequencialContrato(Credenciais Credenciais, DadosConsultaSequencial Dados)
    {
        ConsultarSequencialContratoRequest inValue = new ConsultarSequencialContratoRequest();
        inValue.Credenciais = Credenciais;
        inValue.Dados = Dados;
        ConsultarSequencialContratoResponse retVal = ((RegistroContratoSoap)(this)).ConsultarSequencialContrato(inValue);
        return retVal.ConsultarSequencialContratoResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ConsultarSequencialContratoResponse> RegistroContratoSoap.ConsultarSequencialContratoAsync(ConsultarSequencialContratoRequest request)
    {
        return base.Channel.ConsultarSequencialContratoAsync(request);
    }
    
    public System.Threading.Tasks.Task<ConsultarSequencialContratoResponse> ConsultarSequencialContratoAsync(Credenciais Credenciais, DadosConsultaSequencial Dados)
    {
        ConsultarSequencialContratoRequest inValue = new ConsultarSequencialContratoRequest();
        inValue.Credenciais = Credenciais;
        inValue.Dados = Dados;
        return ((RegistroContratoSoap)(this)).ConsultarSequencialContratoAsync(inValue);
    }
    
    public ResultadoTrocarSenha TrocarSenha(DadosTrocaSenha Dados)
    {
        return base.Channel.TrocarSenha(Dados);
    }
    
    public System.Threading.Tasks.Task<ResultadoTrocarSenha> TrocarSenhaAsync(DadosTrocaSenha Dados)
    {
        return base.Channel.TrocarSenhaAsync(Dados);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AnexarArquivoResponse RegistroContratoSoap.AnexarArquivo(AnexarArquivoRequest request)
    {
        return base.Channel.AnexarArquivo(request);
    }
    
    public ResultadoAnexarArquivo AnexarArquivo(Credenciais Credenciais, DadosAnexarArquivo Dados)
    {
        AnexarArquivoRequest inValue = new AnexarArquivoRequest();
        inValue.Credenciais = Credenciais;
        inValue.Dados = Dados;
        AnexarArquivoResponse retVal = ((RegistroContratoSoap)(this)).AnexarArquivo(inValue);
        return retVal.AnexarArquivoResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<AnexarArquivoResponse> RegistroContratoSoap.AnexarArquivoAsync(AnexarArquivoRequest request)
    {
        return base.Channel.AnexarArquivoAsync(request);
    }
    
    public System.Threading.Tasks.Task<AnexarArquivoResponse> AnexarArquivoAsync(Credenciais Credenciais, DadosAnexarArquivo Dados)
    {
        AnexarArquivoRequest inValue = new AnexarArquivoRequest();
        inValue.Credenciais = Credenciais;
        inValue.Dados = Dados;
        return ((RegistroContratoSoap)(this)).AnexarArquivoAsync(inValue);
    }
}
